### PR TITLE
Add Django IDOM to articles

### PR DESCRIPTION
**Pull request by Archmonger**
Hey Adam,

@rmorshea and I have been hard at work at effectively porting ReactJS to Django. Our project uses a ReactJS client in the front-end, and is pre-configured to communicate with the Django backend via websockets.

Things are in a very usable state right now with no known impactful bugs. 

I was wondering if you'd let us toss a link into your articles page.

### CODE REVIEW

**Comment by Archmonger** [comment]
@adamghill Pinging for PR review in case you have notifications turned off for this repo.

**Comment by adamghill** [comment]
Hey, sorry I missed this before! Does it make sense to add this to the articles or to [here](https://www.django-unicorn.com/docs/#full-stack-framework-python-packages)?

**Comment by Archmonger** [comment]
You're right. Let me redo the placement.

**Comment by Archmonger** [comment]
`IDOM` supports Django, FastAPI, Flask, Sanic, Tornado, Plotly, and Jupyter at the moment.

However, the table currently only has entries for Flask and Django. Do you feel it's appropriate to add in these extra rows?

I don't want to make a large table on your docs just to show our supported platforms without first asking for your permission.

**Comment by adamghill** [comment]
I made https://github.com/adamghill/django-unicorn/pull/356 (the source docs live in the django-unicorn repo). I think I'll take your wording for `IDOM` in the list, but have `django-idom` in the comparison table if that seems ok to you?

**Comment by Archmonger** [comment]
That's good with me!

**Comment by adamghill** [comment]
This got manually merged in https://github.com/adamghill/django-unicorn.com/commit/53fcb9863e7ab3df43d56565e48407bbc40a6926.

**Pull request closed without merging**
